In [1]:
import numpy as np
from scipy.stats import chi2_contingency

In [2]:
df = np.array([[19,6], [43,32]])
df

array([[19,  6],
       [43, 32]])

In [3]:
chi2_contingency(df)

(2.037351443123939,
 0.15347667161786666,
 1,
 array([[15.5,  9.5],
        [46.5, 28.5]]))

On this test the p value is 0.15. So we can confirm that there is not a significant different between men and women


In [4]:
df = np.array([[22,3], [43,32]])
chi2_contingency(df)

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))

On this test the p value is 0.01. So we can confirm that there is a significant different between men and women